"""
C / AVR syntax highlighter za dark editor (VS Code Dark+ paleta).
"""

from PyQt6.QtGui  import QSyntaxHighlighter, QTextCharFormat, QColor, QFont
from PyQt6.QtCore import QRegularExpression as RE


def _fmt(hex_color: str, bold: bool = False, italic: bool = False) -> QTextCharFormat:
    f = QTextCharFormat()
    f.setForeground(QColor(hex_color))
    if bold:   f.setFontWeight(QFont.Weight.Bold)
    if italic: f.setFontItalic(True)
    return f


# ── Colour definitions ────────────────────────────────────────────────────────
FMT_KEYWORD    = _fmt("#569CD6", bold=True)   # void, int, …
FMT_PREPROC    = _fmt("#C586C0", bold=True)   # #include, #define
FMT_INCPATH    = _fmt("#CE9178")              # <avr/io.h>
FMT_AVR_REG    = _fmt("#4EC9B0", bold=True)   # DDRB, TCCR0A, EIMSK …
FMT_AVR_BIT    = _fmt("#9CDCFE")              # WGM01, CS01, PB0, ISC11 …
FMT_FUNC       = _fmt("#DCDCAA")              # sei(), cli()
FMT_NUMBER     = _fmt("#B5CEA8")              # 0x1F, 0b00001101, 42
FMT_COMMENT    = _fmt("#6A9955", italic=True) # /* … */  //


class CHighlighter(QSyntaxHighlighter):
    """Applies AVR-C syntax colouring to a QTextDocument."""

    # Block states for multi-line comment tracking
    _STATE_NORMAL  = -1
    _STATE_COMMENT =  1

    def __init__(self, document):
        super().__init__(document)
        self._rules: list[tuple] = []
        self._ml_start = RE(r'/\*')
        self._ml_end   = RE(r'\*/')
        self._build_rules()

    # ── Rule table ────────────────────────────────────────────────────────────

    def _build_rules(self):
        add = self._rules.append

        # Preprocessor directive keyword
        add((RE(r'^\s*#\s*\w+'), FMT_PREPROC))

        # Include path  <avr/io.h>
        add((RE(r'<[^>\n]+>'), FMT_INCPATH))

        # C keywords
        add((RE(
            r'\b(void|int|uint8_t|uint16_t|uint32_t|unsigned|signed|char|short|long'
            r'|static|const|volatile|return|if|else|while|for|do|break|continue'
            r'|struct|typedef|enum|inline)\b'),
            FMT_KEYWORD))

        # AVR registers — exact names generated by code_gen
        add((RE(
            r'\b(DDR[BCDEF]|PORT[BCDEF]|PIN[BCDEF]'
            r'|TCCR[0134][ABCDE]?'
            r'|OCR[0134][ABCD]'
            r'|ICR[13]|TC4H|TCNT[0134]'
            r'|TIMSK[0134]|TIFR[0134]'
            r'|EICRA|EICRB|EIMSK|EIFR'
            r'|PCICR|PCMSK[012]|PCIFR'
            r'|SREG|MCUCR|USBCON|PLLCSR)\b'),
            FMT_AVR_REG))

        # AVR bit/pin names
        add((RE(
            r'\b(WGM\d{1,2}'
            r'|CS[0134][0-3]'
            r'|COM[0134][ABCD][01]'
            r'|PWM4[ABD]'
            r'|FOC[0134][ABC]'
            r'|ISC[0-36][01]'
            r'|INT[0-6]'
            r'|PCIE[0-2]'
            r'|PCINT[0-9]+'
            r'|ICES\d|ICNC\d'
            r'|P[BCDEF][0-7]'
            r'|MOSI|MISO|SCK|SS|SDA|SCL'
            r'|RXD\d?|TXD\d?|XCK\d?'
            r'|OC[0134][ABCD]'
            r'|ICP[0134])\b'),
            FMT_AVR_BIT))

        # sei() / cli()  — highlight entire call
        add((RE(r'\b(sei|cli)\s*\(\s*\)'), FMT_FUNC))

        # Hex numbers
        add((RE(r'\b0x[0-9A-Fa-f]+\b'), FMT_NUMBER))

        # Binary numbers (our format: 00000001b)
        add((RE(r'\b[01]{8}b\b'), FMT_NUMBER))

        # Decimal integers  (avoid matching inside identifiers)
        add((RE(r'(?<!\w)\d+(?!\w)'), FMT_NUMBER))

        # Single-line comment  //
        add((RE(r'//[^\n]*'), FMT_COMMENT))

        # Inline block comment  /* ... */  (same line only — rest handled below)
        add((RE(r'/\*.*?\*/'), FMT_COMMENT))

    # ── Core method ───────────────────────────────────────────────────────────

    def highlightBlock(self, text: str):
        # 1. Apply all single-line rules
        for pattern, fmt in self._rules:
            it = pattern.globalMatch(text)
            while it.hasNext():
                m = it.next()
                self.setFormat(m.capturedStart(), m.capturedLength(), fmt)

        # 2. Multi-line /* ... */ comments
        self.setCurrentBlockState(self._STATE_NORMAL)

        start = 0
        if self.previousBlockState() != self._STATE_COMMENT:
            m = self._ml_start.match(text)
            start = m.capturedStart() if m.hasMatch() else -1

        while start >= 0:
            end_m = self._ml_end.match(text, start)
            if end_m.hasMatch():
                length = end_m.capturedStart() + end_m.capturedLength() - start
                self.setCurrentBlockState(self._STATE_NORMAL)
            else:
                self.setCurrentBlockState(self._STATE_COMMENT)
                length = len(text) - start
            self.setFormat(start, length, FMT_COMMENT)
            if self.currentBlockState() == self._STATE_COMMENT:
                break
            m = self._ml_start.match(text, start + length)
            start = m.capturedStart() if m.hasMatch() else -1
